// <auto-generated />
using System;
using InterventionsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterventionsApi.Migrations
{
    [DbContext(typeof(InterventionsApiContext))]
    [Migration("20230106184443_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InterventionsApi.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<bool>("Garantie")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("InterventionsApi.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("InterventionsApi.Models.Facture", b =>
                {
                    b.Property<int>("FactureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactureId"), 1L, 1);

                    b.Property<int?>("IntervetionId")
                        .HasColumnType("int");

                    b.Property<double>("MainOeuvre")
                        .HasColumnType("float");

                    b.HasKey("FactureId");

                    b.ToTable("Facture");
                });

            modelBuilder.Entity("InterventionsApi.Models.Intervention", b =>
                {
                    b.Property<int>("InterventionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterventionId"), 1L, 1);

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FactureId")
                        .HasColumnType("int");

                    b.Property<bool>("Gratuit")
                        .HasColumnType("bit");

                    b.Property<int?>("ReclamationId")
                        .HasColumnType("int");

                    b.HasKey("InterventionId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("FactureId")
                        .IsUnique()
                        .HasFilter("[FactureId] IS NOT NULL");

                    b.HasIndex("ReclamationId");

                    b.ToTable("Intervention");
                });

            modelBuilder.Entity("InterventionsApi.Models.Piece", b =>
                {
                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.HasKey("PieceId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Piece");
                });

            modelBuilder.Entity("InterventionsApi.Models.PieceFacturee", b =>
                {
                    b.Property<int>("PieceFactureeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PieceFactureeId"), 1L, 1);

                    b.Property<int?>("PieceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("PieceFactureeId");

                    b.HasIndex("PieceId");

                    b.ToTable("PieceFacturee");
                });

            modelBuilder.Entity("InterventionsApi.Models.Reclamation", b =>
                {
                    b.Property<int>("ReclamationId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReclamationId");

                    b.HasIndex("ClientId");

                    b.ToTable("Reclamation");
                });

            modelBuilder.Entity("InterventionsApi.Models.Intervention", b =>
                {
                    b.HasOne("InterventionsApi.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("InterventionsApi.Models.Facture", "Facture")
                        .WithOne("Intervention")
                        .HasForeignKey("InterventionsApi.Models.Intervention", "FactureId");

                    b.HasOne("InterventionsApi.Models.Reclamation", "Reclamation")
                        .WithMany()
                        .HasForeignKey("ReclamationId");

                    b.Navigation("Article");

                    b.Navigation("Facture");

                    b.Navigation("Reclamation");
                });

            modelBuilder.Entity("InterventionsApi.Models.Piece", b =>
                {
                    b.HasOne("InterventionsApi.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("InterventionsApi.Models.PieceFacturee", b =>
                {
                    b.HasOne("InterventionsApi.Models.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceId");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("InterventionsApi.Models.Reclamation", b =>
                {
                    b.HasOne("InterventionsApi.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("InterventionsApi.Models.Facture", b =>
                {
                    b.Navigation("Intervention");
                });
#pragma warning restore 612, 618
        }
    }
}
